name: cloud_next_flutter_maps
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.1.9
  google_maps_flutter_web: ^0.4.0+1
  http: ^0.13.4
  json_serializable: ^6.3.1
  json_annotation: ^4.6.0
  geolocator: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0
  build_runner: ^2.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/locations.json
